# Generated by Django 4.2.1 on 2023-07-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=244)),
                ('body', models.CharField(default=' ', max_length=244)),
                ('siteType', models.CharField(choices=[('FULL_SITE', 'FULL_SITE'), ('FRONT_BASIC', 'FRONT_BASIC'), ('BACK_BASIC', 'BACK_BASIC')], max_length=64, unique=True, verbose_name='site_type_name')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('createdAt',),
            },
        ),
    ]
